//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EGRESO
    {
        public int ID { get; set; }
        [Required]
        public int Tipo_Egreso { get; set; }
        [Required]
        public int Renglon_Egreso { get; set; }
        [Display( Name ="Tipo_Pago")]
        [Required]
        public int Tipo_Pago { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 5)]
        public string Decripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual EGRESO_RENGLON EGRESO_RENGLON { get; set; }
        public virtual EGRESO_TIPO EGRESO_TIPO { get; set; }
        public virtual PAGO_TIPO PAGO_TIPO { get; set; }
    }
}
