//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasPerEntities : DbContext
    {
        public FinanzasPerEntities()
            : base("name=FinanzasPerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EGRESO> EGRESO { get; set; }
        public virtual DbSet<EGRESO_RENGLON> EGRESO_RENGLON { get; set; }
        public virtual DbSet<EGRESO_TIPO> EGRESO_TIPO { get; set; }
        public virtual DbSet<INGRESO> INGRESO { get; set; }
        public virtual DbSet<INGRESO_TIPO> INGRESO_TIPO { get; set; }
        public virtual DbSet<PAGO_TIPO> PAGO_TIPO { get; set; }
        public virtual DbSet<PROCESO_CORTE> PROCESO_CORTE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TRANSACION> TRANSACION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
