//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO_CORTE
    {
        public int ID { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Mes { get; set; }
        public System.DateTime Fecha_Corte { get; set; }
        public decimal Balance_Inicial { get; set; }
        public decimal Total_ingreso { get; set; }
        public decimal Total_Egreso { get; set; }
        public decimal Balance_corte { get; set; }
        public Nullable<int> Usuario { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
