//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TRANSACION
    {
        public int ID { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 5)]
        public string Tipo_Transacion { get; set; }
        public int Usuario { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 5)]
        public string Evento { get; set; }
        public int Tipo_Pago { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Transacion { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Registro { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        public decimal Monto_Transacion { get; set; }
        [Required]
        public int NO_Tarjeta_CR { get; set; }
        [Required]
        [StringLength(60, MinimumLength = 5)]
        [DataType(DataType.MultilineText)]
        public string Comentario { get; set; }
        public bool Estado { get; set; }
    
        public virtual PAGO_TIPO PAGO_TIPO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
