//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESO_CORTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCESO_CORTE()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Mes { get; set; }
        public System.DateTime Fecha_Corte { get; set; }
        public decimal Balance_Inicial { get; set; }
        public decimal Total_ingreso { get; set; }
        public decimal Total_Egreso { get; set; }
        public decimal Balance_corte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
