//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales_G_
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.TRANSACION = new HashSet<TRANSACION>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public int Limite_Egreso { get; set; }
        public string Tipo_Persona { get; set; }
        public int Fecha_Corte { get; set; }
        public bool Estado { get; set; }
    
        public virtual PROCESO_CORTE PROCESO_CORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACION> TRANSACION { get; set; }
    }
}
